### ISSUE TITLE
Adding libraries from the update site does not work

### ISSUE THREAD

**Issue by MGZeroes** [ModelioOpenSource/Modelio#62]
I have tried to add the JDK library to my project, I have already added the Java Designer module.

When I try to add a library by selecting "Add from update site...", the model components version checker opens with only the message "All model components are up to date". (see picture below).

I suppose this is because the modelio website is under maintenance?

I used this guide from the modeliosoft website:
https://www.modeliosoft.com/modelio-help/41/en/index.jsp?topic=%2Forg.modelio.documentation.modeliomodeler%2Fhtml%2FModeler-_modeler_managing_projects_configuring_project_libraries.html

Thanks in advance.

![image](https://user-images.githubusercontent.com/36378780/233049515-b8557d1a-8ef3-432c-bdca-ff5e77911745.png)

**Comment by IrinaNeculita** [comment]
Hi, 
The update site is currently down, so we have published the Modelio libraries here :
https://github.com/ModelioOpenSource/ExtensionsForModelio/releases/tag/5.3.1

Now you can download and deploy them in your project, using the "Add from local file..." button, instead of "Add from update site". 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/130666068/233357482-061b8022-9fed-41a7-bfbf-aa911c7eca64.png)

Regards, 
Irina.
